language: ruby
rvm:
- 2.3.1
addons:
  sauce_connect: true
install:
- nvm install 4.0
- npm install -g nightwatch
- bundle
before_script:
- bundle exec rackup -p 9291
script:
- nightwatch --config spec/nightwatch.js
- pkill node
env:
  global:
  - secure: WFT4VpnjZBC9i8FtDxd15wsNzRkSXwE2QDs76L1EFHyytILqN2kZm97k1Kn51O7vgm5b5mCAsl59y9HJ92VNksNUd5IdZhsJwZVyKF4ubBIg4YqBcBFY9Tcrr7GJeLHblApX7+mFzz+0gZ2/RmhuREiMv/qZu6mAnq2j2Gnksd0WsMEPEx0zJGDX4YMCja9gXo46SZoFim4c/AlYm6yL2s50dO0OrY0u9zaLhoV3QI1vsYu6OVRnsvDGl5q9sKhkhC2HsgoILn5j+kjZtj6OwOm4sYHLtuaJ350uTuuEQ/dpS/hT1glIq3LHns2V2OaYPSB5gtb6CL+m4UMcrZ0ya7lniXrwqzY9Cdfa8FbGseBKg4RjVhuk+Uvk5Oa2C66VCBt/Cm+SNKBFPfrIDpsVB375ji/OnO60BKHw1E3lhsgEf71arI0LbFbK9nsGUPLFzCgXrDnjG0kSBR1eZPW3p5GT3zjptJSHpHwXyGPxa4PnCKRkG1cH0FG2O8Auedx9tG7s4qeADEkrI+rbyZjUV0zciRiQ4dATaR1wQ73OlK1HAX8U1eaKTf+fwBviYuHGJhqYSgy+UWh18Y4dK6u8VRsGb3YW+0VlkypjtDyNx2xaSoKH8HG7+CqeclcLti55Bx7uUsuvnmDKrrwFW8qBXbY73RrI+Ren+z4THHdKPIM=
  - secure: fbbZryqsZuaLLMdy1WphXsvd7nAK+yzGj5qox3gsBrEha/XSa7XnHh0SEtnUZGs83R3gNt0GKj6NfdQD68RzkCsCQYLNjkGbuYpcVeGlY51aFTzgete1c31njE1StMGpbawHmHmepr82xtx6mLCsLfp3uzB6YVvEhHtkG3AizKKDI0msQFX3XAc0TxoEvqL5J5xEKqytd5xKplBaGBRCiB9wvqNcgIsyT5yPp0e/3Cudwt2DHNDntZhn8maPewYSHWFDpYRVhzEFvzGbixm4CUmPWWIeGgtfzqlDSqMzF5GDKtZkX+Zp5Eh6V7BTWEurhMQKJ695CHQaiEMm6ZHRPsM1s79LQqB9SICrsX9j4j/MhWlBK0h3SBzHr3hf/cflnYJpNhsdwCgihRiJSHyInqrCRZpCFCpY0QQB1NqBPXb0uhLIsxbDAYngD3QygNhBC/mo1O4WNBlkkgz/87jscyPOoh+G2XGfm8CaSEWiwtmSdXr0B7H1ESvSxhS82T/VfPRfU6ijXa56MqnQuBCjakDckaLOHXaJ0gQbdn/6YMwXHDAx9AaVjKzGvJyoNjFWEX/eA2N46w9X7oJERKPOyWKDz0V4w9fP0uLaXry4cJL6caQ9CoR2u96wE6DL/Di14+jLZcZ7Xti4FphrvMfZlhB+iacMaupHaKOp+Y9ZSFg=
